project:
  type: book

lang: de

book:
  title: "Vorlesungsnotizen zu Numerik für Informatiker"
  author:
    - name: Nicolas Gres
      affiliation:
        name: Karlsruher Institut für Technologie
        url: https://www.kit.edu
      email: nicolas.gres@student.kit.edu
  date: today
  chapters:
    - index.qmd
    - 01-arithmetik.ipynb
    - 02-lgs.ipynb
    - 03-fitting.ipynb
    - 04-eigenwerte.ipynb
    - appendix.qmd
    - references.qmd
  sidebar: 
    title: 🧮 Numerik
    tools:
      - icon: discord
        href: https://discord.com/channels/501365485837877268/632976659280035893
  repo-url: https://github.com/nico0302/kit-num
  comments: 
    giscus:
      repo: nico0302/kit-num
  site-url: https://nico0302.github.io/kit-num
  page-footer: 
    center: 
      - text: "Nicolas Gres - 2025"
  
execute:
  freeze: auto

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: styles.css
  pdf:
    documentclass: scrreprt