project:
  type: book

lang: de

book:
  title: "Vorlesungsnotizen zu Numerik für Informatiker"
  author:
    - name: Nicolas Gres
      affiliation:
        name: Karlsruher Institut für Technologie
        url: https://www.kit.edu
      email: nicolas.gres@student.kit.edu
  date: today
  chapters:
    - index.qmd
    - 01-arithmetik.ipynb
    - 02-lgs.ipynb
    - appendix.qmd
    - references.qmd
  sidebar: 
    title: 🧮 KIT NUM
  repo-url: https://github.com/nico0302/kit-num
  comments: 
    utterances:
      repo: nico0302/kit-num
  
execute:
  freeze: auto

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt