# Appendix {.unnumbered}

## Mathematische Grundlagen

### Analysis

#### Reihen und Summen

**Geometrische Reihe**

Für alle reellen $q \neq 1$ und für alle $n \in \mathbb{N}_0$ ist:

$$
\sum_{k=0}^n q^k=\frac{1-q^{n+1}}{1-q}
$$

Der Grenzwert ist dementsprechend:

$$
\sum_{k=0}^{\infty} q^k=\frac{1}{1-q}
$$

**Taylor-Formel**

Sei $f \in C^{k+1}([a, b])$ und $x_0 \in [a, b]$. Dann gilt für jedes $x \in [a, b]$:

\begin{align*}
f(x) &=f(x_0) + f'(x_0)(x-x_0) + \frac{f''(x_0)}{2!}(x-x_0)^2 + \ldots + \frac{f^{(k)}(x_0)}{k!}(x-x_0)^k + R_{k+1}(x_0) \\
&= \sum_{j=0}^k \frac{f^{(j)}(x_0)}{j!}(x-x_0)^j + R_{k+1}(x_0)
\end{align*}

wobei der *Restglied* $R_{k+1}(x_0)$ in der *Lagrange-Form* gegeben ist durch:

$$
R_{k+1}(x_0)=\frac{1}{(k+1)!}f^{(k+1)}(\xi)(x-x_0)^{k+1}
$$

#### Logarithmen

{{< video https://www.youtube.com/watch?v=SYxyemNSSm8 >}}

### Lineare Algebra

{{< video https://www.youtube.com/watch?v=mhy-ZKSARxI >}}


#### Orthogonale Matrizen

Eine Matrix $Q$ ist orthogonal, wenn:   

$$
Q^\top Q = Q Q^\top = I
$$


- $Q^\top = Q^{-1}$
    - $Q$ ist daher auch **invertierbar**
- $det(Q) = \pm 1$

#### Symmetrische Matrizen

Eine Matrix $S$ ist symmetrisch, wenn:

$$
S^\top = S
$$

- Die Eigenwerte von $S$ sind reell
    - Die Eigenvektoren von $S$ sind orthogonal zueinander
- $S^\top S = S S^\top$ (normal)
- Sei $A \in \mathbb{R}^{N \times N}$, dann ist $B=A^\top A$ symmetrisch
- $S$ ist **nicht notwendigerweise** invertierbar


**$2\times2$-Matrix invertieren**

$$
A=\left(\begin{array}{ll}
a & b \\
c & d
\end{array}\right) \quad \text { then } \quad A^{-1}=\frac{1}{a d-b c}\left(\begin{array}{cc}
d & -b \\
-c & a
\end{array}\right)
$$