[project]
name = "kit-num"
version = "0.1.0"
description = "Lecture notes for KIT's T-MATH-102242"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.29.5",
    "matplotlib>=3.10.3",
    "numpy>=2.2.6",
    "scipy>=1.15.3",
]
